### ISSUE TITLE
[Forge]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/Therrassium#2]
**Make sure you are on the latest version before requesting a feature**
Done

I sent you an issue about 3 days ago about forge compatibility:
![Screenshot_20220102-051014_GitHub.png](https://user-images.githubusercontent.com/90295730/147865968-57a8879a-2211-4268-96f8-9c4587671ec2.png)
And i really want to point out that i really really want to have this posibility. I've recently been thinking about making a modpack (via the curseforge app (forge))
So can you please make a forge version of every mod version? You've told me that it was posible to do so. You can call the file for example **therrassium 1.1 forge** or **therrassium 1.1 fabric** on curseforge so you can keep it all in 1 project on curseforge. I would very much appreciate you doing this. 

-JustIanJ

**Comment by karstenzip** [comment]
As I said, I won't port this to Forge
