### ISSUE TITLE
[Rei compatibility]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/Therrassium#4]
**Make sure you are on the latest version before requesting a feature**

**Is your feature request related to a problem? Please describe.**
Personally i use therrassium in combi with rei (roughly enough items) here you can usualy see crafting recipes for smithing table to crafting table. But for therrassium it doesnt show.

**Describe the solution you'd like**
To add this to rei

**Additional context**

**Comment by karstenzip** [comment]
The recipes do show up in REI

**Comment by JustIanJ** [comment]
They do not for me?
