### ISSUE TITLE
[BUG] [1.18.2] Crash on client startup

### ISSUE THREAD

**Issue by kwpugh** [codeman1o1/Therrassium#5]
Crash report:  https://gist.github.com/kwpugh/4f8254593826ae084d19d13ff6c64930

Your mixin into ExperienceOrbEntityMixin is failing.  I think you have the notation incorrect.  I don't think you need the V argument.

@Inject(at = @At("HEAD"), method = "onPlayerCollision()V")

**Comment by kwpugh** [comment]
Also, it is good practice to add your mod name into the method name to avoid confusion.

	@Inject(at = @At("HEAD"), method = "onPlayerCollision")
	public void gobberCheckForMedallion(PlayerEntity player, CallbackInfo ci)

**Comment by kwpugh** [comment]
This is the problem:
![Screen Shot 2022-03-14 at 12 39 43 PM](https://user-images.githubusercontent.com/8809210/158229937-979045ee-9de6-4a77-b19f-bc2041c2cf31.png)

I changed it to this and updated your Loom to 0.11 (recommended for 1.18+
![Screen Shot 2022-03-14 at 12 40 41 PM](https://user-images.githubusercontent.com/8809210/158230103-9722ce54-de33-48c7-b0b3-6c6fb178fb9b.png)

No build errors or crashes after that.

**Comment by karstenzip** [comment]
Working on it!

**Comment by kwpugh** [comment]
Given the high damage/durability and such in the mod, it might make it more versatile for players if you add a config system to adjust the tool/armor values and effect durations and such.

Good work so far.

**Comment by karstenzip** [comment]
That was already on my todo list ;)

**Comment by kwpugh** [comment]
I use Cloth Config API across all my mods and have found it very easy to implement.

**Comment by kwpugh** [comment]
Nice, thanks.

Also, have config options for each effect in the block would be nice for tailoring.  Good luck.
