### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by karstenzip** [codeman1o1/Therrassium#6]
**Describe the bug**
Crash on start:
`net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.minecraft.util.Identifier net.minecraft.util.registry.RegistryKey.method_29177()'`

**Expected behavior**
Launch game without errors

**Additional context**
I think it has to do with the update from 1.18.1 to 1.18.2

**Comment by codeman1o1** [comment]
[latest.log](https://github.com/codeman1o1/Therrassium/files/8247605/latest.log)

**Comment by karstenzip** [comment]
[latest.log](https://github.com/codeman1o1/Therrassium/files/8247610/latest.log)

**Comment by karstenzip** [comment]
Tested outside of development environment and didn't crash
